Storing System/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'reports/generate_order_4z-customer'

  get 'reports/generate_order_4_operator'

  get 'edit_order/add'

  get 'edit_order/find'

  get 'edit_order/update'

  get 'edit_order/delete'

  resources :orders

  get 'edit_customer/add'

  get 'edit_customer/find'

  get 'edit_customer/update'

  get 'edit_customer/delete'

  resources :customers

  get 'edit_product/add'

  get 'edit_product/find'

  get 'edit_product/update'

  get 'edit_product/delete'

  resources :products

  get 'home/new'

  get 'home/show'

  get 'home/index'

end

Storing System/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
end

Storing System/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
end

Storing System/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders

end

Storing System/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Storing System/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customer_id, :customer_firstName, :customer_lastName, :customer_relationship, :street_number, :street_name, :district, :province, :postcode, :mobile_number, :age_group, :gender, :has_child, :child_age_group)
    end
end

Storing System/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end

  def show
  end

  def index
  end
end

Storing System/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @products = Product.all
    @customers = Customer.all
  end

  # GET /orders/1/edit
  def edit
    @products = Product.all
    @customers = Customer.all
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @products = Product.all
    @customers = Customer.all
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_id, :customer_id, :product_id, :product_quantity, :order_date, :delivery_fee_rmb, :discount, :unit_price_rmb, :total_cost_rmb, :total_price_rmb)
    end
end

Storing System/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_id, :product_name, :product_description, :product_brand, :product_standard, :cost_aud, :cost_rmb, :unit_price_aud, :unit_price_rmb, :margin_aud, :margin_rmb, :stock_au, :stock_cn)
    end
end

Storing System/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def generate_order_4z-customer
  end

  def generate_order_4_operator
  end
end

Storing System/app/helpers/application_helper.rb
module ApplicationHelper
end

Storing System/app/helpers/customers_helper.rb
module CustomersHelper
end

Storing System/app/helpers/home_helper.rb
module HomeHelper
end

Storing System/app/helpers/orders_helper.rb
module OrdersHelper
end

Storing System/app/helpers/products_helper.rb
module ProductsHelper
end

Storing System/app/helpers/reports_helper.rb
module ReportsHelper
end

Storing System/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :customer_Name %><br>
    <%= f.text_area :customer_firstName %>
  </div>
  <div class="field">
    <%= f.label :customer_IDNumber %><br>
    <%= f.text_area :IDNumber %>
  </div>
  <div class="field">
    <%= f.label :customer_relationship %><br>
    <%= f.text_area :customer_relationship %>
  </div>
  <div class="field">
    <%= f.label :street_number %><br>
    <%= f.text_area :street_number %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br>
    <%= f.text_area :street_name %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_area :district %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_area :province %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :mobile_number %><br>
    <%= f.text_field :mobile_number %>
  </div>
  <div class="field">
    <%= f.label :age_group %><br>
    <%= f.text_area :age_group %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_area :gender %>
  </div>
  <div class="field">
    <%= f.label :has_child %><br>
    <%= f.text_field :has_child %>
  </div>
  <div class="field">
    <%= f.label :child_age_group %><br>
    <%= f.text_area :child_age_group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Storing System/app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

Storing System/app/views/customers/index.html.erb
<head>
  <style>
      table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
      }
  </style>
</head>

<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Customer firstname</th>
      <th>Customer lastname</th>
      <th>Customer relationship</th>
      <th>Street number</th>
      <th>Street name</th>
      <th>District</th>
      <th>Province</th>
      <th>Postcode</th>
      <th>Mobile number</th>
      <th>Age group</th>
      <th>Gender</th>
      <th>Has child</th>
      <th>Child age group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.customer_id %></td>
        <td><%= customer.customer_firstName %></td>
        <td><%= customer.customer_lastName %></td>
        <td><%= customer.customer_relationship %></td>
        <td><%= customer.street_number %></td>
        <td><%= customer.street_name %></td>
        <td><%= customer.district %></td>
        <td><%= customer.province %></td>
        <td><%= customer.postcode %></td>
        <td><%= customer.mobile_number %></td>
        <td><%= customer.age_group %></td>
        <td><%= customer.gender %></td>
        <td><%= customer.has_child %></td>
        <td><%= customer.child_age_group %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>
<%= link_to 'Home', home_index_path %>

Storing System/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

Storing System/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @customer.customer_id %>
</p>

<p>
  <strong>Customer firstname:</strong>
  <%= @customer.customer_firstName %>
</p>

<p>
  <strong>Customer lastname:</strong>
  <%= @customer.customer_lastName %>
</p>

<p>
  <strong>Customer relationship:</strong>
  <%= @customer.customer_relationship %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @customer.street_number %>
</p>

<p>
  <strong>Street name:</strong>
  <%= @customer.street_name %>
</p>

<p>
  <strong>District:</strong>
  <%= @customer.district %>
</p>

<p>
  <strong>Province:</strong>
  <%= @customer.province %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @customer.postcode %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @customer.mobile_number %>
</p>

<p>
  <strong>Age group:</strong>
  <%= @customer.age_group %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @customer.gender %>
</p>

<p>
  <strong>Has child:</strong>
  <%= @customer.has_child %>
</p>

<p>
  <strong>Child age group:</strong>
  <%= @customer.child_age_group %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

Storing System/app/views/home/index.html.erb
<head>
  <style>
    p{
        text-align: center;
    }
    a{
        margin-top:20px;
        margin-botton:20px;
        margin-left:auto;
        margin-right:auto;
        text-align: center;
        border:1px solid #2E2F30;
        background-color: #FFFFFF;
        font-size: 18pt;
        border-radius:5px;
        display:block;
        text-decoration: none;
        padding: 5px;
        width:300px;

    }
    .edit {
        width: 100px;
        display: inline;
        alignment: center;
        margin-left: 5px;
        margin-right: 5px;

    }
    .report{
        width:200px;
        display: inline;
        alignment: center;
        margin-left: 5px;
        margin-right: 5px;
    }
  </style>
</head>

<body>
    <h1 style="text-align: center;">Sarah's Pharmacy</h1>
    <p>Product page</p>
    <a href="/products">Show product details</a>
    <br>
    <p style="padding-bottom: 10px;">Edit Product</p>
    <div style="margin:0 auto; width:70px;">
        <a class="edit" href="/products/new">Add</a>
    </div>
    <br>
    <p>Customer page</p>
    <a href="/customers">Show customer details</a>
    <br>
    <p style="padding-bottom: 10px;">Edit Customer</p>
    <div style="margin:0 auto; width:70px;">
        <a class="edit" href="/customers/new">Add</a>
    </div>
    <br>
    <p>Order page</p>
    <a href="/orders">Show orders</a>
    <br>
    <p style="padding-bottom: 10px;">Edit orders</p>
    <div style="margin:0 auto; width:70px;">
        <a class="edit" href="/orders/new">Add</a>
    </div>
    <br>
    <p style="padding-bottom: 10px;">Report page</p>
    <div style="margin:0 auto; width:370px;">
        <a class="report" href="/reports/generate_order_4z-customer">For Customer</a>
        <a class="report" href="/reports/generate_order_4_operator">For Operator</a>
    </div>
    <br>
</body>

Storing System/app/views/home/new.html.erb
<h1>Home#new</h1>
<p>Find me in app/views/home/new.html.erb</p>

Storing System/app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

Storing System/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoringSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Storing System/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, @customers, :customer_firstName,:customer_firstName, include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, @products, :product_name, :product_name, include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :product_quantity %><br>
    <%= f.text_field :product_quantity %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.date_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :delivery_fee_rmb %><br>
    <%= f.text_field :delivery_fee_rmb %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :unit_price_rmb %><br>
    <%= f.text_field :unit_price_rmb %>
  </div>
  <div class="field">
    <%= f.label :total_price_rmb %><br>
    <%= f.text_field :total_price_rmb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Storing System/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

Storing System/app/views/orders/index.html.erb
<head>
  <style>
      table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
      }
  </style>
</head>

<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Customer</th>
      <th>Product</th>
      <th>Product quantity</th>
      <th>Order date</th>
      <th>Delivery fee rmb</th>
      <th>Discount</th>
      <th>Unit price rmb</th>
      <th>Total cost rmb</th>
      <th>Total price rmb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.customer_id %></td>
        <td><%= order.product_id %></td>
        <td><%= order.product_quantity %></td>
        <td><%= order.order_date %></td>
        <td><%= order.delivery_fee_rmb %></td>
        <td><%= order.discount %></td>
        <td><%= order.unit_price_rmb %></td>
        <td><%= order.total_cost_rmb %></td>
        <td><%= order.total_price_rmb %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<%= link_to 'Home', home_index_path %>

Storing System/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

Storing System/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order.order_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<p>
  <strong>Product quantity:</strong>
  <%= @order.product_quantity %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>Delivery fee rmb:</strong>
  <%= @order.delivery_fee_rmb %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @order.discount %>
</p>

<p>
  <strong>Unit price rmb:</strong>
  <%= @order.unit_price_rmb %>
</p>

<p>
  <strong>Total cost rmb:</strong>
  <%= @order.total_cost_rmb %>
</p>

<p>
  <strong>Total price rmb:</strong>
  <%= @order.total_price_rmb %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

Storing System/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_area :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_description %><br>
    <%= f.text_area :product_description %>
  </div>
  <div class="field">
    <%= f.label :product_brand %><br>
    <%= f.text_area :product_brand %>
  </div>
  <div class="field">
    <%= f.label :product_standard %><br>
    <%= f.text_area :product_standard %>
  </div>
  <div class="field">
    <%= f.label :cost_aud %><br>
    <%= f.text_field :cost_aud %>
  </div>
  <div class="field">
    <%= f.label :cost_rmb %><br>
    <%= f.text_field :cost_rmb %>
  </div>
  <div class="field">
    <%= f.label :unit_price_aud %><br>
    <%= f.text_field :unit_price_aud %>
  </div>
  <div class="field">
    <%= f.label :unit_price_rmb %><br>
    <%= f.text_field :unit_price_rmb %>
  </div>
  <div class="field">
    <%= f.label :margin_aud %><br>
    <%= f.text_field :margin_aud %>
  </div>
  <div class="field">
    <%= f.label :margin_rmb %><br>
    <%= f.text_field :margin_rmb %>
  </div>
  <div class="field">
    <%= f.label :stock_au %><br>
    <%= f.text_field :stock_au %>
  </div>
  <div class="field">
    <%= f.label :stock_cn %><br>
    <%= f.text_field :stock_cn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Storing System/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back to list', products_path %>

Storing System/app/views/products/index.html.erb
<head>
  <style>
      table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
      }
  </style>
</head>

<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Product name</th>
      <th>Product description</th>
      <th>Product brand</th>
      <th>Product standard</th>
      <th>Cost aud</th>
      <th>Cost rmb</th>
      <th>Unit price aud</th>
      <th>Unit price rmb</th>
      <th>Margin aud</th>
      <th>Margin rmb</th>
      <th>Stock au</th>
      <th>Stock cn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_id %></td>
        <td><%= product.product_name %></td>
        <td><%= product.product_description %></td>
        <td><%= product.product_brand %></td>
        <td><%= product.product_standard %></td>
        <td><%= product.cost_aud %></td>
        <td><%= product.cost_rmb %></td>
        <td><%= product.unit_price_aud %></td>
        <td><%= product.unit_price_rmb %></td>
        <td><%= product.margin_aud %></td>
        <td><%= product.margin_rmb %></td>
        <td><%= product.stock_au %></td>
        <td><%= product.stock_cn %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
<%= link_to 'Home', home_index_path %>

Storing System/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

Storing System/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product.product_id %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product description:</strong>
  <%= @product.product_description %>
</p>

<p>
  <strong>Product brand:</strong>
  <%= @product.product_brand %>
</p>

<p>
  <strong>Product standard:</strong>
  <%= @product.product_standard %>
</p>

<p>
  <strong>Cost aud:</strong>
  <%= @product.cost_aud %>
</p>

<p>
  <strong>Cost rmb:</strong>
  <%= @product.cost_rmb %>
</p>

<p>
  <strong>Unit price aud:</strong>
  <%= @product.unit_price_aud %>
</p>

<p>
  <strong>Unit price rmb:</strong>
  <%= @product.unit_price_rmb %>
</p>

<p>
  <strong>Margin aud:</strong>
  <%= @product.margin_aud %>
</p>

<p>
  <strong>Margin rmb:</strong>
  <%= @product.margin_rmb %>
</p>

<p>
  <strong>Stock au:</strong>
  <%= @product.stock_au %>
</p>

<p>
  <strong>Stock cn:</strong>
  <%= @product.stock_cn %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back to list', products_path %>

Storing System/app/views/reports/generate_order_4_operator.html.erb
<h1>Reports#generate_order_4_operator</h1>
<p>Find me in app/views/reports/generate_order_4_operator.html.erb</p>

Storing System/app/views/reports/generate_order_4z-customer.html.erb
<h1>Reports#generate_order_4z-customer</h1>
<p>Find me in app/views/reports/generate_order_4z-customer.html.erb</p>